// Sample product data with images, prices, and descriptions
const products = [
    { id: 1, name: 'Baby Banana USA', category: 'fruits', price: 0.99, description: 'Per unit', image: '../pictures/produceimages/babybananausa.png' },
    { id: 2, name: 'Banana Manzano', category: 'fruits', price: 1.19, description: 'Per unit', image: '../pictures/produceimages/bananamanzano.png' },
    { id: 3, name: 'Thai Banana', category: 'fruits', price: 1.49, description: 'Per unit', image: '../pictures/produceimages/thaibanana.png' },
    { id: 4, name: 'Banana USA', category: 'fruits', price: 0.79, description: 'Per unit', image: '../pictures/produceimages/bananausa.png' },
    { id: 5, name: 'Green Banana', category: 'fruits', price: 0.89, description: 'Per unit', image: '../pictures/produceimages/greenbanana.png' },
    { id: 6, name: 'Burro Banana', category: 'fruits', price: 1.29, description: 'Per unit', image: '../pictures/produceimages/burrobanana.png' },
    { id: 7, name: 'Plantains Banana', category: 'fruits', price: 1.99, description: 'Per unit', image: '../pictures/produceimages/plantainsbanana.png' },
    { id: 8, name: 'Red Banana', category: 'fruitsi', price: 1.79, description: 'Per unit', image: '../pictures/produceimages/redbanana.png' },
    { id: 9, name: 'Fuji Apple USA', category: 'fruits', price: 1.49, description: 'Per unit', image: '../pictures/produceimages/fujiappleusa.png' },
    { id: 10, name: 'Red Apple USA', category: 'fruits', price: 1.29, description: 'Per unit', image: '../pictures/produceimages/redappleusa.png' },
    { id: 11, name: 'Gala Apple USA', category: 'fruits', price: 1.39, description: 'Per unit', image: '../pictures/produceimages/galaappleusa.png' },
    { id: 12, name: 'Gala Apple Small', category: 'fruits', price: 1.09, description: 'Per unit', image: '../pictures/produceimages/galaapplesmall.png' },
    { id: 13, name: 'Honeycrisp Apples', category: 'fruits', price: 2.49, description: 'Per unit', image: '../pictures/produceimages/honeycrispapples.png' },
    { id: 14, name: 'Golden Apple USA', category: 'fruits', price: 1.59, description: 'Per unit', image: '../pictures/produceimages/goldenappleusa.png' },
    { id: 15, name: 'Green Apple USA', category: 'fruits', price: 1.69, description: 'Per unit', image: '../pictures/produceimages/greenappleusa.png' },
    { id: 16, name: 'Pink Lady Apples', category: 'fruits', price: 2.19, description: 'Per unit', image: '../pictures/produceimages/pinkladyapples.png' },
    { id: 17, name: 'Pinata Apple', category: 'fruits', price: 1.89, description: 'Per unit', image: '../pictures/produceimages/pinataapple.png' },
    { id: 18, name: 'Satsuma USA', category: 'fruits', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/satsumausa.png' },
    { id: 19, name: 'Tangerine Peru', category: 'fruits', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/tangerineperu.png' },
    { id: 20, name: 'Blood Orange', category: 'fruits', price: 1.99, description: 'Per lb', image: '../pictures/produceimages/bloodorange.png' },
    { id: 21, name: 'Orange Cara', category: 'fruits', price: 1.89, description: 'Per lb', image: '../pictures/produceimages/orangecara.png' },
    { id: 22, name: 'Minneola Orange', category: 'fruits', price: 2.29, description: 'Per lb', image: '../pictures/produceimages/minneolaorange.png' },
    { id: 23, name: 'Orange USA', category: 'fruits', price: 1.59, description: 'Per lb', image: '../pictures/produceimages/orangeusa.png' },
    { id: 24, name: 'Sour Orange', category: 'fruits', price: 1.99, description: 'Per lb', image: '../pictures/produceimages/sourorange.png' },
    { id: 25, name: 'Sweet Limes', category: 'fruits', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/sweetlimes.png' },
    { id: 26, name: 'Grapefruit USA', category: 'fruits', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/grapefruitusa.png' },
    { id: 27, name: 'Pummelo USA', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/pummelousa.png' },
    { id: 28, name: 'Oro Blanco Fruit', category: 'fruits', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/oroblancofruit.png' },
    { id: 29, name: 'Asian Pear', category: 'fruits', price: 2.99, description: 'Per unit', image: '../pictures/produceimages/asianpear.png' },
    { id: 30, name: 'Korean Singo', category: 'fruits', price: 2.79, description: 'Per unit', image: '../pictures/produceimages/koreansingo.png' },
    { id: 31, name: 'Sand Pear USA', category: 'fruits', price: 1.99, description: 'Per unit', image: '../pictures/produceimages/sandpearusa.png' },
    { id: 32, name: 'Fragrant Pear', category: 'fruits', price: 2.49, description: 'Per unit', image: '../pictures/produceimages/fragrantpear.png' },
    { id: 33, name: 'Yali Pear China', category: 'fruits', price: 2.79, description: 'Per unit', image: '../pictures/produceimages/yalipearchina.png' },
    { id: 34, name: 'Red Cherry', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/redcherry.png' },
    { id: 35, name: 'Golden Cherry', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/goldencherry.png' },
    { id: 36, name: 'Green Papaya', category: 'fruits', price: 1.79, description: 'Per unit', image: '../pictures/produceimages/greenpapaya.png' },
    { id: 37, name: 'Yellow Papaya', category: 'fruits', price: 1.99, description: 'Per unit', image: '../pictures/produceimages/yellowpapaya.png' },
    { id: 38, name: 'Royal Star Papaya', category: 'fruits', price: 2.49, description: 'Per unit', image: '../pictures/produceimages/royalstarpapaya.png' },
    { id: 39, name: 'Large Jackfruit', category: 'fruits', price: 5.99, description: 'Per unit', image: '../pictures/produceimages/largejackfruit.png' },
    { id: 40, name: 'Baby JackFruit', category: 'fruits', price: 3.99, description: 'Per unit', image: '../pictures/produceimages/babyjackfruit.png' },
    { id: 41, name: 'Durian', category: 'fruits', price: 14.99, description: 'Per unit', image: '../pictures/produceimages/durian.png' },
    { id: 42, name: 'Red Dragon Fruit', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/reddragonfruit.png' },
    { id: 43, name: 'White Dragon Fruit', category: 'fruits', price: 4.79, description: 'Per unit', image: '../pictures/produceimages/whitedragonfruit.png' },
    { id: 44, name: 'Yellow Dragon Fruit', category: 'fruits', price: 5.49, description: 'Per unit', image: '../pictures/produceimages/yellowdragonfruit.png' },
    { id: 45, name: 'Stem Longan', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/stemlongan.png' },
    { id: 46, name: 'Loose Lychee', category: 'fruits', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/looselychee.png' },
    { id: 47, name: 'Rambutan', category: 'fruits', price: 6.49, description: 'Per lb', image: '../pictures/produceimages/rambutan.png' },
    { id: 48, name: 'Thai Guava', category: 'fruits', price: 2.29, description: 'Per unit', image: '../pictures/produceimages/thaiguava.png' },
    { id: 49, name: 'Mexican Guava', category: 'fruits', price: 2.99, description: 'Per unit', image: '../pictures/produceimages/mexicanguava.png' },
    { id: 50, name: 'Cherimoyas Chile', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/cherimoyaschile.png' },
    { id: 51, name: 'Soursop', category: 'fruits', price: 6.99, description: 'Per unit', image: '../pictures/produceimages/soursop.png' },
    { id: 52, name: 'Breadfruit', category: 'fruits', price: 3.79, description: 'Per unit', image: '../pictures/produceimages/breadfruit.png' },
    { id: 53, name: 'Persimmon USA', category: 'fruits', price: 2.49, description: 'Per unit', image: '../pictures/produceimages/persimmonusa.png' },
    { id: 54, name: 'Hachiya', category: 'fruits', price: 2.79, description: 'Per unit', image: '../pictures/produceimages/hachiya.png' },
    { id: 55, name: 'Yellow Nectarine', category: 'fruits', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/yellownectarine.png' },
    { id: 56, name: 'White Nectarine', category: 'fruits', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/whitenectarine.png' },
    { id: 57, name: 'Yellow Peach USA', category: 'fruits', price: 2.89, description: 'Per lb', image: '../pictures/produceimages/yellowpeachusa.png' },
    { id: 58, name: 'White Peach USA', category: 'fruits', price: 3.19, description: 'Per lb', image: '../pictures/produceimages/whitepeachusa.png' },
    { id: 59, name: 'Plum USA', category: 'fruits', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/plumusa.png' },
    { id: 60, name: 'Black Plum USA', category: 'fruits', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/blackplumusa.png' },
    { id: 61, name: 'Green Plum', category: 'fruits', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/greenplum.png' },
    { id: 62, name: 'Sugar Plum', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/sugarplum.png' },
    { id: 63, name: 'Apricot', category: 'fruits', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/apricot.png' },
    { id: 64, name: 'Hami Melon', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/hamimelon.png' },
    { id: 65, name: 'Gaya Melon', category: 'fruits', price: 4.79, description: 'Per unit', image: '../pictures/produceimages/gayamelon.png' },
    { id: 66, name: 'Korean Melon', category: 'fruits', price: 4.49, description: 'Per unit', image: '../pictures/produceimages/koreanmelon.png' },
    { id: 67, name: 'Pepino Melon', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/pepinomelon.png' },
    { id: 68, name: 'Red Grape USA', category: 'fruits', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/redgrapeusa.png' },
    { id: 69, name: 'Black Grape', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/blackgrape.png' },
    { id: 70, name: 'Red Seeded Grape', category: 'fruits', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/redseededgrape.png' },
    { id: 71, name: 'Green Grape', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/greengrape.png' },
    { id: 72, name: 'Muscadine Grape', category: 'fruits', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/muscadinegrape.png' },
    { id: 73, name: 'Peony Grapes', category: 'fruits', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/peonygrapes.png' },
    { id: 74, name: 'Yellow Dates', category: 'fruits', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/yellowdates.png' },
    { id: 75, name: 'Jujube', category: 'fruits', price: 6.29, description: 'Per lb', image: '../pictures/produceimages/jujube.png' },
    { id: 76, name: 'Mango', category: 'fruits', price: 1.99, description: 'Per unit', image: '../pictures/produceimages/mango.png' },
    { id: 77, name: 'Green Mango', category: 'fruits', price: 2.49, description: 'Per unit', image: '../pictures/produceimages/greenmango.png' },
    { id: 78, name: 'Thai Mango', category: 'fruits', price: 2.99, description: 'Per unit', image: '../pictures/produceimages/thaimango.png' },
    { id: 79, name: 'Green Baby Mango', category: 'fruits', price: 3.29, description: 'Per unit', image: '../pictures/produceimages/greenbabymango.png' },
    { id: 80, name: 'Yellow Baby Mango', category: 'fruits', price: 3.49, description: 'Per unit', image: '../pictures/produceimages/yellowbabymango.png' },
    { id: 81, name: 'June Plum USA', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/juneplumusa.png' },
    { id: 82, name: 'Loquat', category: 'fruits', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/loquat.png' },
    { id: 83, name: 'Mangosteen', category: 'fruits', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/mangosteen.png' },
    { id: 84, name: 'Pecan Nuts', category: 'nuts', price: 6.49, description: 'Per lb', image: '../pictures/produceimages/pecannuts.png' },
    { id: 85, name: 'Walnut', category: 'nuts', price: 6.79, description: 'Per lb', image: '../pictures/produceimages/walnut.png' },
    { id: 86, name: 'Chestnut USA', category: 'nuts', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/chestnutusa.png' },
    { id: 87, name: 'Peanut USA', category: 'nuts', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/peanutusa.png' },
    { id: 88, name: 'Green Peanuts', category: 'nuts', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/greenpeanuts.png' },
    { id: 89, name: 'Fresh Fig', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/freshfig.png' },
    { id: 90, name: 'Custard Apple', category: 'fruits', price: 5.29, description: 'Per unit', image: '../pictures/produceimages/custardapple.png' },
    { id: 91, name: 'Cactus Pear USA', category: 'fruits', price: 3.99, description: 'Per unit', image: '../pictures/produceimages/cactuspearusa.png' },
    { id: 92, name: 'Pomegranate USA', category: 'fruits', price: 2.99, description: 'Per unit', image: '../pictures/produceimages/pomegranateusa.png' },
    { id: 93, name: 'Mamey', category: 'fruits', price: 4.49, description: 'Per unit', image: '../pictures/produceimages/mamey.png' },
    { id: 94, name: 'Quenepa', category: 'fruits', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/quenepa.png' },
    { id: 95, name: 'Wax Apple', category: 'fruits', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/waxapple.png' },
    { id: 96, name: 'Eggfruit', category: 'fruits', price: 5.49, description: 'Per unit', image: '../pictures/produceimages/eggfruit.png' },
    { id: 97, name: 'Sugar Apple', category: 'fruits', price: 5.99, description: 'Per unit', image: '../pictures/produceimages/sugarapple.png' },
    { id: 98, name: 'Star Apple USA', category: 'fruits', price: 6.49, description: 'Per unit', image: '../pictures/produceimages/starappleusa.png' },
    { id: 99, name: 'Key Lime USA', category: 'fruits', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/keylimeusa.png' },
    { id: 100, name: 'Pluots', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/pluots.png' },
    { id: 101, name: 'Lemon Plum', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/lemonplum.png' },
    { id: 102, name: 'Cherry Plum', category: 'fruits', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/cherryplum.png' },
    { id: 103, name: 'Tejocote', category: 'fruits', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/tejocote.png' },
    { id: 104, name: 'Passion Fruit', category: 'fruits', price: 6.49, description: 'Per lb', image: '../pictures/produceimages/passionfruit.png' },
    { id: 105, name: 'Sour Plum', category: 'fruits', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/sourplum.png' },
    { id: 106, name: 'Red Anjou Pear', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/redanjoupear.png' },
    { id: 107, name: 'Ciruelas', category: 'fruits', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/ciruelas.png' },
    { id: 108, name: 'Taiwan Melon', category: 'fruits', price: 5.79, description: 'Per unit', image: '../pictures/produceimages/taiwanmelon.png' },
    { id: 109, name: 'Star Fruit', category: 'fruits', price: 3.49, description: 'Per unit', image: '../pictures/produceimages/starfruit.png' },
    { id: 110, name: 'Bean Sprout USA', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/beansproutusa.png' },
    { id: 111, name: 'Soybean Sprout', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/soybeansprout.png' },
    { id: 112, name: 'China Ginger', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/chinaginger.png' },
    { id: 113, name: 'Galanga', category: 'vegetables', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/galanga.png' },
    { id: 114, name: 'Turmeric USA', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/turmericusa.png' },
    { id: 115, name: 'Garlic', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/garlic.png' },
    { id: 116, name: 'Peeled Garlic', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/peeledgarlic.png' },
    { id: 117, name: 'Tomato Loose USA', category: 'vegetables', price: 2.29, description: 'Per lb', image: '../pictures/produceimages/tomatolooseusa.png' },
    { id: 118, name: 'Roma Tomato', category: 'vegetables', price: 1.99, description: 'Per lb', image: '../pictures/produceimages/romatomato.png' },
    { id: 119, name: 'Green Tomato', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/greentomato.png' },
    { id: 120, name: 'Tomatoes on Vine', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/tomatoesonvine.png' },
    { id: 121, name: 'String Bean', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/stringbean.png' },
    { id: 122, name: 'Long Valor Bean', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/longvalorbean.png' },
    { id: 123, name: 'Roma Bean', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/romabean.png' },
    { id: 124, name: 'Sugar Snap Pea', category: 'vegetables', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/sugarsnappea.png' },
    { id: 125, name: 'Chickpea', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/chickpea.png' },
    { id: 126, name: 'Flat Valor Bean', category: 'vegetables', price: 4.19, description: 'Per lb', image: '../pictures/produceimages/flatvalorbean.png' },
    { id: 127, name: 'Fava Bean', category: 'vegetables', price: 3.89, description: 'Per lb', image: '../pictures/produceimages/favabean.png' },
    { id: 128, name: 'Flower Bean', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/flowerbean.png' },
    { id: 129, name: 'White Long Bean', category: 'vegetables', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/whitelongbean.png' },
    { id: 130, name: 'Green Long Bean', category: 'vegetables', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/greenlongbean.png' },
    { id: 131, name: 'Beans Guar', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/beansguar.png' },
    { id: 132, name: 'A Okra', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/aokra.png' },
    { id: 133, name: 'Snow Pea', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/snowpea.png' },
    { id: 134, name: 'Parval', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/parval.png' },
    { id: 135, name: 'Lotus Root', category: 'vegetables', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/lotusroot.png' },
    { id: 136, name: 'Water Chestnut', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/waterchestnut.png' },
    { id: 137, name: 'Graffiti Eggplant', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/graffitieggplant.png' },
    { id: 138, name: 'Phil Eggplant', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/phileggplant.png' },
    { id: 139, name: 'Chinese Eggplant', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/chineseeggplant.png' },
    { id: 140, name: 'Indian Eggplant', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/indianeggplant.png' },
    { id: 141, name: 'Thai White Eggplant', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/thaiwhiteeggplant.png' },
    { id: 142, name: 'American Eggplant', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/americaneggplant.png' },
    { id: 143, name: 'Persian Cucumber', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/persiancucumber.png' },
    { id: 144, name: 'Japanese Cucumber', category: 'vegetables', price: 3.19, description: 'Per lb', image: '../pictures/produceimages/japanesecucumber.png' },
    { id: 145, name: 'Pickle USA', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/pickleusa.png' },
    { id: 146, name: 'Cucumber USA', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/cucumberusa.png' },
    { id: 147, name: 'White Cucumber', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/whitecucumber.png' },
    { id: 148, name: 'Bitter Cucumber', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/bittercucumber.png' },
    { id: 149, name: 'White Bitter Cucumber', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/whitebittercucumber.png' },
    { id: 150, name: 'Indian Bitter', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/indianbitter.png' },
    { id: 151, name: 'Chinese Bitter', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/chinesebitter.png' },
    { id: 152, name: 'Korea Cucumber', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/koreacucumber.png' },
    { id: 153, name: 'Muop Huong', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/muophuong.png' },
    { id: 154, name: 'Thai Okra', category: 'vegetables', price: 3.89, description: 'Per lb', image: '../pictures/produceimages/thaiokra.png' },
    { id: 155, name: 'Snake Gourd', category: 'vegetables', price: 3.69, description: 'Per lb', image: '../pictures/produceimages/snakegourd.png' },
    { id: 156, name: 'Fuzzy Melon', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/fuzzymelon.png' },
    { id: 157, name: 'Chayote Costa', category: 'vegetables', price: 2.89, description: 'Per lb', image: '../pictures/produceimages/chayotecosta.png' },
    { id: 158, name: 'Zucchini', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/zucchini.png' },
    { id: 159, name: 'Mexican Squash', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/mexicansquash.png' },
    { id: 160, name: 'Tatuma Squash', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/tatumasquash.png' },
    { id: 161, name: 'Carrot USA', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/carrotusa.png' },
    { id: 162, name: 'Daikon Japanese', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/daikonjapanese.png' },
    { id: 163, name: 'Daikon Korean', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/daikonkorean.png' },
    { id: 164, name: 'Chinese Daikon', category: 'vegetables', price: 2.89, description: 'Per lb', image: '../pictures/produceimages/chinesedaikon.png' },
    { id: 165, name: 'Indian Squash', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/indiansquash.png' },
    { id: 166, name: 'Black Radish', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/blackradish.png' },
    { id: 167, name: 'Purple Daikon', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/purpledaikon.png' },
    { id: 168, name: 'Malanga', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/malanga.png' },
    { id: 169, name: 'Malanga Islena', category: 'vegetables', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/malangaislena.png' },
    { id: 170, name: 'Malanga Blanca', category: 'vegetables', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/malangablanca.png' },
    { id: 171, name: 'Small Taro', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/smalltaro.png' },
    { id: 172, name: 'Jicama', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/jicama.png' },
    { id: 173, name: 'Kohlrabi', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/kohlrabi.png' },
    { id: 174, name: 'Beets USA', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/beetsusa.png' },
    { id: 175, name: 'Purple Top Turnip USA', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/purpletoptturnipusa.png' },
    { id: 176, name: 'Watermelon Turnip', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/watermelonturnip.png' },
    { id: 177, name: 'Winter Melon', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/wintermelon.png' },
    { id: 178, name: 'Pumpkin USA', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/pumpkinusa.png' },
    { id: 179, name: 'Kabocha USA', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/kabochausa.png' },
    { id: 180, name: 'Acorn Squash', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/acornsquash.png' },
    { id: 181, name: 'Sweet Kabocha', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/sweetkabocha.png' },
    { id: 182, name: 'Rutabaga', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/rutabaga.png' },
    { id: 183, name: 'Round Opo', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/roundopo.png' },
    { id: 184, name: 'Butternut', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/butternut.png' },
    { id: 185, name: 'Spaghetti Squash', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/spaghettisquash.png' },
    { id: 186, name: 'Yellow Squash', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/yellowsquash.png' },
    { id: 187, name: 'Bengali Squash', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/bengalisquash.png' },
    { id: 188, name: 'Korean Squash', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/koreansquash.png' },
    { id: 189, name: 'Yellow Onion USA', category: 'vegetables', price: 1.99, description: 'Per lb', image: '../pictures/produceimages/yellowonionusa.png' },
    { id: 190, name: 'Sweet Onion', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/sweetonion.png' },
    { id: 191, name: 'Red Onion USA', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/redonionusa.png' },
    { id: 192, name: 'White Onion USA', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/whiteonionusa.png' },
    { id: 193, name: 'Shallot USA', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/shallotusa.png' },
    { id: 194, name: 'Potato USA', category: 'vegetables', price: 1.99, description: 'Per lb', image: '../pictures/produceimages/potatousa.png' },
    { id: 195, name: 'Red Potato USA', category: 'vegetables', price: 2.29, description: 'Per lb', image: '../pictures/produceimages/redpotatousa.png' },
    { id: 196, name: 'White Potato USA', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/whitepotatousa.png' },
    { id: 197, name: 'Creamer Red Grapes', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/creamerredgrapes.png' },
    { id: 198, name: 'Creamer White Grapes', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/creamerwhitegrapes.png' },
    { id: 199, name: 'Japanese Sweet Potato', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/japanesesweetpotato.png' },
    { id: 200, name: 'Sweet Potato USA', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/sweetpotatousa.png' },
    { id: 201, name: 'Red Sweet Potato', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/redsweetpotato.png' },
    { id: 202, name: 'Purple Yam White', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/purpleyamwhite.png' },
    { id: 203, name: 'Purple Yam', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/purpleyam.png' },
    { id: 204, name: 'Ratalu Purple Yam', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/ratalupurpleyam.png' },
    { id: 205, name: 'Yucca Root', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/yuccaroot.png' },
    { id: 206, name: 'Yellow Yam USA', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/yellowyamusa.png' },
    { id: 207, name: 'Ghana Yam USA', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/ghanayamusa.png' },
    { id: 208, name: 'Yampi USA', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/yampiusa.png' },
    { id: 209, name: 'Boniato Yam', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/boniatoyam.png' },
    { id: 210, name: 'White Yam', category: 'vegetables', price: 4.69, description: 'Per lb', image: '../pictures/produceimages/whiteyam.png' },
    { id: 211, name: 'Green Bell Pepper', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/greenbellpepper.png' },
    { id: 212, name: 'Yellow Bell Pepper', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/yellowbellpepper.png' },
    { id: 213, name: 'Red Bell Pepper', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/redbellpepper.png' },
    { id: 214, name: 'Orange Bell Pepper', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/orangebellpepper.png' },
    { id: 215, name: 'Mixed Bell Pepper', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/mixedbellpepper.png' },
    { id: 216, name: 'Poblano Bushell', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/poblanobushell.png' },
    { id: 217, name: 'Anaheim Pepper Mexico', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/anaheimpeppermexico.png' },
    { id: 218, name: 'Cubanelle Pepper', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/cubanellepepper.png' },
    { id: 219, name: 'Banana Pepper', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/bananapepper.png' },
    { id: 220, name: 'Banana Chili Peppers', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/bananachilipeppers.png' },
    { id: 221, name: 'Jalapeno Peppers', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/jalapenopeppers.png' },
    { id: 222, name: 'Red Jalapeno Peppers', category: 'vegetables', price: 3.29, description: 'Per lb', image: '../pictures/produceimages/redjalapenopeppers.png' },
    { id: 223, name: 'Serrano Chili Peppers', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/serranochilipeppers.png' },
    { id: 224, name: 'Red Fresno Chili Peppers', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/redfresnochilipeppers.png' },
    { id: 225, name: 'Cowhorn Peppers', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/cowhornpeppers.png' },
    { id: 226, name: 'Korean Chili Peppers', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/koreanchilipeppers.png' },
    { id: 227, name: 'Chilaca Peppers', category: 'vegetables', price: 4.79, description: 'Per lb', image: '../pictures/produceimages/chilacapeppers.png' },
    { id: 228, name: 'Green Indian Chili Peppers', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/greenindianchilipeppers.png' },
    { id: 229, name: 'Red Indian Chili Peppers', category: 'vegetables', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/redindianchilipeppers.png' },
    { id: 230, name: 'Shishito Peppers', category: 'vegetables', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/shishitopeppers.png' } ,
    { id: 231, name: 'Green Habanero Chili Peppers', category: 'vegetables', price: 5.49, description: 'Per lb', image: '../pictures/produceimages/greenhabanerochilipeppers.png' },
    { id: 232, name: 'Red Habanero Chili Peppers', category: 'vegetables', price: 5.79, description: 'Per lb', image: '../pictures/produceimages/redhabanerochilipeppers.png' },
    { id: 233, name: 'Orange Habanero Chili Peppers', category: 'vegetables', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/orangehabanerochilipeppers.png' },
    { id: 234, name: 'Scotch Bonnet USA', category: 'vegetables', price: 6.29, description: 'Per lb', image: '../pictures/produceimages/scotchbonnetusa.png' },
    { id: 235, name: 'Red Thai Chili Peppers', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/redthaichilipeppers.png' },
    { id: 236, name: 'Green Thai Chili Peppers', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/greenthaichilipeppers.png' },
    { id: 237, name: 'Mix Thai Chili Peppers', category: 'vegetables', price: 5.29, description: 'Per lb', image: '../pictures/produceimages/mixthaichilipeppers.png' },
    { id: 238, name: 'Ghost Peppers', category: 'vegetables', price: 6.99, description: 'Per lb', image: '../pictures/produceimages/ghostpeppers.png' },
    { id: 239, name: 'White Mushrooms', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/whitemushrooms.png' },
    { id: 240, name: 'Flower Shiitake Mushrooms', category: 'vegetables', price: 6.99, description: 'Per lb', image: '../pictures/produceimages/flowershiitakemushrooms.png' },
    { id: 241, name: 'Shiitake Mushrooms', category: 'vegetables', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/shiitakemushrooms.png' },
    { id: 242, name: 'Chinese Oysters', category: 'vegetables', price: 7.49, description: 'Per lb', image: '../pictures/produceimages/chineseoysters.png' },
    { id: 243, name: 'King Oysters', category: 'vegetables', price: 6.99, description: 'Per lb', image: '../pictures/produceimages/kingoysters.png' },
    { id: 244, name: 'Portobello Mushroom', category: 'vegetables', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/portobellomushroom.png' },
    { id: 245, name: 'Nagaimo', category: 'vegetables', price: 6.29, description: 'Per lb', image: '../pictures/produceimages/nagaimo.png' },
    { id: 246, name: 'Gobo Burdock', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/goboburdock.png' },
    { id: 247, name: 'Celery Root', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/celeryroot.png' },
    { id: 248, name: 'Japanese Eggplant', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/japaneseeggplant.png' },
    { id: 249, name: 'Shredded Papaya', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/shreddedpapaya.png' },
    { id: 250, name: 'Drumsticks', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/drumsticks.png' },
    { id: 251, name: 'Fresh Bamboo Shoots In Water', category: 'vegetables', price: 5.99, description: 'Per lb', image: '../pictures/produceimages/freshbambooshootsinwater.png' },
    { id: 252, name: 'Peeled Lotus Root', category: 'vegetables', price: 6.49, description: 'Per lb', image: '../pictures/produceimages/peeledlotusroot.png' },
    { id: 253, name: 'Pickled Vegetable', category: 'vegetables', price: 4.99, description: 'Per lb', image: '../pictures/produceimages/pickledvegetable.png' },
    { id: 254, name: 'Sweet Sour Leek', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/sweetsourleek.png' },
    { id: 255, name: 'Pickled Mustard', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/pickledmustard.png' },
    { id: 256, name: 'Green Onion', category: 'vegetables', price: 2.49, description: 'Per lb', image: '../pictures/produceimages/greenonion.png' },
    { id: 257, name: 'Mexican Green Onion', category: 'vegetables', price: 2.79, description: 'Per lb', image: '../pictures/produceimages/mexicangreenonion.png' },
    { id: 258, name: 'Cilantro', category: 'vegetables', price: 1.99, description: 'Per bunch', image: '../pictures/produceimages/cilantro.png' },
    { id: 259, name: 'Ginger', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/ginger.png' },
    { id: 260, name: 'Garlic', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/garlic.png' },
    { id: 261, name: 'Endive Lettuce', category: 'vegetables', price: 3.49, description: 'Per head', image: '../pictures/produceimages/endivelettuce.png' },
    { id: 262, name: 'Escarole Lettuce', category: 'vegetables', price: 3.79, description: 'Per head', image: '../pictures/produceimages/escarolelettuce.png' },
    { id: 263, name: 'Boston Lettuce', category: 'vegetables', price: 3.79, description: 'Per head', image: '../pictures/produceimages/bostonlettuce.png' },
    { id: 264, name: 'Celery', category: 'vegetables', price: 2.99, description: 'Per bunch', image: '../pictures/produceimages/celery.png' },
    { id: 265, name: 'Fresh Spinach', category: 'vegetables', price: 3.29, description: 'Per bunch', image: '../pictures/produceimages/freshspinach.png' },
    { id: 266, name: 'Watercress', category: 'vegetables', price: 2.99, description: 'Per bunch', image: '../pictures/produceimages/watercress.png' },
    { id: 267, name: 'Collard Green', category: 'vegetables', price: 3.49, description: 'Per bunch', image: '../pictures/produceimages/collardgreen.png' },
    { id: 268, name: 'Kale', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/kale.png' },
    { id: 269, name: 'Radish', category: 'vegetables', price: 2.79, description: 'Per bunch', image: '../pictures/produceimages/radish.png' },
    { id: 270, name: 'Yellow Corn', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/yellowcorn.png' } ,
    { id: 271, name: 'Curly Parsley', category: 'vegetables', price: 2.29, description: 'Per bunch', image: '../pictures/produceimages/curlyparsley.png' },
    { id: 272, name: 'Lemon Grass', category: 'vegetables', price: 2.79, description: 'Per bunch', image: '../pictures/produceimages/lemongrass.png' },
    { id: 273, name: 'Lettuce Romaine', category: 'vegetables', price: 3.29, description: 'Per head', image: '../pictures/produceimages/lettuceromaine.png' },
    { id: 274, name: 'Cello Iceberg', category: 'vegetables', price: 3.49, description: 'Per head', image: '../pictures/produceimages/celloiceberg.png' },
    { id: 275, name: 'Lettuce Green Leaf', category: 'vegetables', price: 3.29, description: 'Per head', image: '../pictures/produceimages/lettucegreenleaf.png' },
    { id: 276, name: 'Red Leaf Lettuce', category: 'vegetables', price: 3.29, description: 'Per head', image: '../pictures/produceimages/redleaflettuce.png' },
    { id: 277, name: 'Cauliflower', category: 'vegetables', price: 4.99, description: 'Per head', image: '../pictures/produceimages/cauliflower.png' },
    { id: 278, name: 'Chonggak Ponytail White Radish', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/chonggakponytailwhiteradish.png' },
    { id: 279, name: 'Yeolmu Radish', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/yeolmuradish.png' },
    { id: 280, name: 'Escarole Lettuce', category: 'vegetables', price: 3.79, description: 'Per head', image: '../pictures/produceimages/escarolelettuce.png' },
    { id: 281, name: 'White Corn', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/whitecorn.png' },
    { id: 282, name: 'Yellow Lemon', category: 'fruits', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/yellowlemon.png' },
    { id: 283, name: 'Lime', category: 'fruits', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/lime.png' },
    { id: 284, name: 'Avocado', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/avocado.png' },
    { id: 285, name: 'Green Kiwi', category: 'fruits', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/greenkiwi.png' },
    { id: 286, name: 'Golden Kiwi', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/goldenkiwi.png' },
    { id: 287, name: 'Red Kiwi', category: 'fruits', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/redkiwi.png' },
    { id: 288, name: 'Mango', category: 'fruits', price: 2.99, description: 'Per unit', image: '../pictures/produceimages/mango.png' },
    { id: 289, name: 'Manila Mango Box', category: 'fruits', price: 12.99, description: 'Per box', image: '../pictures/produceimages/manilamangobox.png' },
    { id: 290, name: 'Mexican Mango', category: 'fruits', price: 3.49, description: 'Per unit', image: '../pictures/produceimages/mexicanmango.png' },
    { id: 291, name: 'Thai Mango', category: 'fruits', price: 3.99, description: 'Per unit', image: '../pictures/produceimages/thaimango.png' },
    { id: 292, name: 'Green Coconut', category: 'fruits', price: 5.49, description: 'Per unit', image: '../pictures/produceimages/greencoconut.png' },
    { id: 293, name: 'Dry Coconut', category: 'fruits', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/drycoconut.png' },
    { id: 294, name: 'Artichokes', category: 'vegetables', price: 3.99, description: 'Per unit', image: '../pictures/produceimages/artichokes.png' },
    { id: 295, name: 'Pineapple', category: 'fruits', price: 5.99, description: 'Per unit', image: '../pictures/produceimages/pineapple.png' },
    { id: 296, name: 'BOSC Pear', category: 'fruits', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/boscpear.png' },
    { id: 297, name: 'D Anjou', category: 'fruits', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/danjou.png' },
    { id: 298, name: 'Sugarcane', category: 'vegetables', price: 6.49, description: 'Per bundle', image: '../pictures/produceimages/sugarcane.png' },
    { id: 299, name: 'Watermelon', category: 'fruits', price: 7.99, description: 'Per unit', image: '../pictures/produceimages/watermelon.png' },
    { id: 300, name: 'Honeydew', category: 'fruits', price: 6.49, description: 'Per unit', image: '../pictures/produceimages/honeydew.png' },
    { id: 301, name: 'Cantaloupe', category: 'fruits', price: 5.49, description: 'Per unit', image: '../pictures/produceimages/cantaloupe.png' },
    { id: 302, name: 'Hami Melon', category: 'fruits', price: 6.99, description: 'Per unit', image: '../pictures/produceimages/hamimelon.png' },
    { id: 303, name: 'Cacao Fruit', category: 'fruits', price: 7.99, description: 'Per unit', image: '../pictures/produceimages/cacaofruit.png' },
    { id: 304, name: 'Leek', category: 'vegetables', price: 3.49, description: 'Per bunch', image: '../pictures/produceimages/leek.png' },
    { id: 305, name: 'Aloe Vera', category: 'vegetables', price: 4.99, description: 'Per unit', image: '../pictures/produceimages/aloevera.png' },
    { id: 306, name: 'Balut / Salted Duck Eggs', category: 'eggs', price: 6.49, description: 'Per pack', image: '../pictures/produceimages/balut.png' },
    { id: 307, name: 'Fresh Duck Eggs', category: 'eggs', price: 5.99, description: 'Per dozen', image: '../pictures/produceimages/freshduckeggs.png' },
    { id: 308, name: 'Asparagus', category: 'vegetables', price: 4.99, description: 'Per bunch', image: '../pictures/produceimages/asparagus.png' },
    { id: 309, name: 'Shallot', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/shallot.png' },
    { id: 310, name: 'Beets with Leaves', category: 'vegetables', price: 3.49, description: 'Per bunch', image: '../pictures/produceimages/beetswithleaves.png' },
    { id: 311, name: 'Green Dandelion', category: 'vegetables', price: 2.99, description: 'Per bunch', image: '../pictures/produceimages/greendandelion.png' },
    { id: 312, name: 'Swiss Chard', category: 'vegetables', price: 3.29, description: 'Per bunch', image: '../pictures/produceimages/swisschard.png' },
    { id: 313, name: 'Methi Leaf', category: 'vegetables', price: 2.79, description: 'Per bunch', image: '../pictures/produceimages/methileaf.png' },
    { id: 314, name: 'Epazote', category: 'vegetables', price: 3.49, description: 'Per bunch', image: '../pictures/produceimages/epazote.png' },
    { id: 315, name: 'Fennel', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/fennel.png' },
    { id: 316, name: 'Green Huaje', category: 'vegetables', price: 4.29, description: 'Per bunch', image: '../pictures/produceimages/greenhuaje.png' },
    { id: 317, name: 'Huauzontle', category: 'vegetables', price: 3.79, description: 'Per bunch', image: '../pictures/produceimages/huauzontle.png' },
    { id: 318, name: 'Broccoli', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/broccoli.png' },
    { id: 319, name: 'Japanese Cucumber', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/japanesecucumber.png' },
    { id: 320, name: 'Dills', category: 'vegetables', price: 2.79, description: 'Per bunch', image: '../pictures/produceimages/dills.png' },
    { id: 321, name: 'Shanghai Bok', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/shanghaibok.png' },
    { id: 322, name: 'Bok Choy Jr', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/bokchoyjr.png' },
    { id: 323, name: 'Big Gai Choy', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/BigGaiChoy.png' },
    { id: 324, name: 'Small Gai Choy', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/smallgaichoy.png' },
    { id: 325, name: 'Baby Bok Choy', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/babybokchoy.png' },
    { id: 326, name: 'Baby Bok Choy Jr', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/babybokchoyjr.png' },
    { id: 327, name: 'Sweet Bok Choy', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/sweetbokchoy.png' },
    { id: 328, name: 'Long Bok Choy Jr', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/longbokchoyjr.png' },
    { id: 329, name: 'Nira Greens', category: 'vegetables', price: 3.49, description: 'Per bunch', image: '../pictures/produceimages/niragreens.png' },
    { id: 330, name: 'Chive Flowers', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/chiveflowers.png' },
    { id: 331, name: 'Gai Lan', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/gailan.png' },
    { id: 332, name: 'Gai Lan Jr', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/gailanjr.png' },
    { id: 333, name: 'Ong Choy', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/ongchoy.png' },
    { id: 334, name: 'Yam Leaf USA', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/yamleafusa.png' },
    { id: 335, name: 'Montoi USA', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/montoiusa.png' },
    { id: 336, name: 'Chinese Celery', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/chinesecelery.png' },
    { id: 337, name: 'Sher-Li-Hon Greens', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/Sher-Li-HonGreens.png' },
    { id: 338, name: 'Tong Ho Leaf', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/tongholeaf.png' },
    { id: 339, name: 'Pea Sprouts Small', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/peasproutssmall.png' },
    { id: 340, name: 'Yu Choy', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/yuchoy.png' },
    { id: 341, name: 'Yu Choy Sum', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/yuchoysum.png' },
    { id: 342, name: 'Rau Leaves', category: 'vegetables', price: 3.79, description: 'Per bunch', image: '../pictures/produceimages/rauleaves.png' },
    { id: 343, name: 'Callaloo', category: 'vegetables', price: 4.29, description: 'Per bunch', image: '../pictures/produceimages/callaloo.png' },
    { id: 344, name: 'Taiwan Spinach', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/taiwanspinach.png' },
    { id: 345, name: 'Napa Cabbage', category: 'vegetables', price: 3.49, description: 'Per lb', image: '../pictures/produceimages/napacabbage.png' },
    { id: 346, name: 'Cabbage', category: 'vegetables', price: 2.99, description: 'Per lb', image: '../pictures/produceimages/cabbage.png' },
    { id: 347, name: 'Taiwan Cabbage', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/taiwancabbage.png' },
    { id: 348, name: 'Savoy Cabbage', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/savoycabbage.png' },
    { id: 349, name: 'Brussel Sprouts', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/brusselsprouts.png' },
    { id: 350, name: 'Red Cabbage', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/redcabbage.png' },
    { id: 351, name: 'Broccoli Crown', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/broccolicrown.png' },
    { id: 352, name: 'Ta Ku Choy', category: 'vegetables', price: 3.79, description: 'Per lb', image: '../pictures/produceimages/takuchoy.png' },
    { id: 353, name: 'Long Napa', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/longnapa.png' },
    { id: 354, name: 'Pumpkin Leaf', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/pumpkinleaf.png' },
    { id: 355, name: 'Hierba Mora', category: 'vegetables', price: 3.79, description: 'Per bunch', image: '../pictures/produceimages/hierbamora.png' },
    { id: 356, name: 'Yucca Leaf', category: 'vegetables', price: 4.49, description: 'Per bunch', image: '../pictures/produceimages/yuccaleaf.png' },
    { id: 357, name: 'Jute Leaf / RAU', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/Jute LeafOrRAU.png' },
    { id: 358, name: 'Bo Ngot / Sweet Leaves', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/BoNgotOrSweet Leaves.png' },
    { id: 359, name: 'Chipilin Leaf', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/chipilinleaf.png' },
    { id: 360, name: 'Nira Yellow', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/nirayellow.png' },
    { id: 361, name: 'Garlic Stem', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/garlicstem.png' },
    { id: 362, name: 'Winged Bean', category: 'vegetables', price: 4.29, description: 'Per lb', image: '../pictures/produceimages/wingedbean.png' },
    { id: 363, name: 'Bok Choy Purple', category: 'vegetables', price: 4.49, description: 'Per lb', image: '../pictures/produceimages/bokchoypurple.png' },
    { id: 364, name: 'Banana Leaf', category: 'vegetables', price: 4.99, description: 'Per bunch', image: '../pictures/produceimages/bananaleaf.png' },
    { id: 365, name: 'Banana Stem', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/bananastem.png' },
    { id: 366, name: 'Garlic Leaves', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/garlicleaves.png' },
    { id: 367, name: 'Mango Leaves', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/mangoleaves.png' },
    { id: 368, name: 'Broccolini', category: 'vegetables', price: 4.99, description: 'Per bunch', image: '../pictures/produceimages/broccolini.png' },
    { id: 369, name: 'Moringa Leaf', category: 'vegetables', price: 4.29, description: 'Per bunch', image: '../pictures/produceimages/moringaleaf.png' },
    { id: 370, name: 'Pandan Leaf', category: 'vegetables', price: 4.49, description: 'Per bunch', image: '../pictures/produceimages/pandanleaf.png' },
    { id: 371, name: 'Taro Leaf', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/taroleaf.png' },
    { id: 372, name: 'Green Grass Jelly Leaf', category: 'vegetables', price: 3.99, description: 'Per bunch', image: '../pictures/produceimages/greengrassjellyleaf.png' },
    { id: 373, name: 'Daikon with Leaves', category: 'vegetables', price: 3.99, description: 'Per lb', image: '../pictures/produceimages/daikonwithleaves.png' }

];

// Function to display products with description and price
function displayProducts(productsToDisplay) {
    const productList = document.getElementById('product-list');
    productList.innerHTML = ''; // Clear previous products
    productsToDisplay.forEach(product => {
        const productDiv = document.createElement('div');
        productDiv.classList.add('product-item');
        productDiv.innerHTML = `
              <img src="${product.image}" alt="${product.name}">
            <h4>${product.name}</h4>
            <p class="price">$${product.price.toFixed(2)}</p>
            <p class="description">${product.description}</p>
            
        `;
        productList.appendChild(productDiv);
    });
}

// Initial display of all products
displayProducts(products);

// Price Label Update
function updatePriceLabel(value) {
    document.getElementById('price-label').textContent = `$${value}`;
}

// Filter Functionality
document.getElementById('price-range').addEventListener('input', function() {
    filterProducts();
});

document.getElementById('category-filter').addEventListener('change', function() {
    filterProducts();
});

// Filtering products by price and category
function filterProducts() {
    const priceLimit = parseFloat(document.getElementById('price-range').value);
    const selectedCategory = document.getElementById('category-filter').value;

    const filteredProducts = products.filter(product => {
        const priceMatch = product.price <= priceLimit;
        const categoryMatch = selectedCategory === 'all' || product.category === selectedCategory;
        return priceMatch && categoryMatch;
    });

    displayProducts(filteredProducts); // Display filtered products
}
