name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]          # deploy only when main is updated
  pull_request:                 # optional: create a preview channel for every PR
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout source code
      - uses: actions/checkout@v4

      # 2 Set up Node (needed for firebase-tools)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3 Install Firebase CLI
      - run: npm install -g firebase-tools

      # 4 Deploy
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting \
                          --token "$FIREBASE_TOKEN" \
                          ${FIREBASE_PROJECT_ID:+--project "$FIREBASE_PROJECT_ID"}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
